kind: pipeline
name: default

steps:
- name: update_theme
  image: alpine
  environment:
    SSH_USER:
      from_secret: SSH_USER
    SSH_PASS:
      from_secret: SSH_PASS
    SSH_IP:
      from_secret: SSH_IP
  commands:
  - apk update
  - apk add openssh sshpass
  - sshpass -p $$SSH_PASS ssh -o StrictHostKeyChecking=no $$SSH_USER@$$SSH_IP "./update_qnipsel.sh"
  when:
    branch:
    - master
