image: alpine:latest

stages:
    - build
    - deploy

before_script:
    - apk update

build_npm:
    stage: build
    only: 
        - master
    script:
        - apk add npm
        - npm install
        - npm run css-main
    artifacts:
        paths:
            - dist/

build_php:
    stage: build
    only:
        - master
    script:
        - apk add composer
        - composer install
    artifacts:
        paths:
            - vendor/

release:
    stage: deploy
    only:
        - master
    dependencies:
        - build_npm
        - build_php
    script:
        - apk add openssh sshpass
        - rm -rf .git build node_modules scss
        - sshpass -p $SSH_PASS scp -r -o StrictHostKeyChecking=no . $SSH_USER@$SSH_IP:html/qnipsel/wp-content/themes/templateq
