image: alpine:latest

stages:
    - build
    - deploy

before_script:
    - apk update
    - apk add npm composer openssh sshpass

build_npm:
    stage: build
    only: 
        - master
    script:
        - npm install
        - npm run css-main

build_php:
    stage: build
    only:
        - master
    script: composer install

release:
    stage: deploy
    only:
        - master
    script:
        - rm -rf .git build node_modules scss
        - sshpass -p $SSH_PASS scp -r -o StrictHostKeyChecking=no . $SSH_USER@$SSH_IP:html/qnipsel/wp-content/themes/templateq
