stages:
  - deploy

deploy_production:
  stage: deploy
  image: tetraweb/php:7.1
  before_script:
    - "which sshpass || ( apt-get update -y && apt-get install sshpass -y )"
  script:
    - sshpass -p $STAGING_SSH_PASS ssh p424439@p424439.mittwaldserver.info "cd /home/www/p424439/html/wordpress/wp-content/themes/templateQ && git pull"
  only:
    - master
