stages:
  - deploy

deploy_production:
  stage: deploy
  image: tetraweb/php:7.1
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install ssh-agent -y )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh p424439@p424439.mittwaldserver.info "cd /home/www/p424439/html/wordpress/wp-content/themes/templateQ && git pull"
  only:
    - master
