version: '3.3'

services:
    db:
        container_name: 'qnipsel-db'
        image: 'mysql:5.7'
        volumes:
            - './docker/data/mysql:/var/lib/mysql'
        ports:
            - 18766:3306
        environment:
            MYSQL_ROOT_PASSWORD: qnipseldb
            MYSQL_DATABASE: wordpress_db
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: wordpress_password

    phpmyadmin:
        container_name: 'qnipsel-phpmyadmin'
        depends_on:
            - db
        image: 'phpmyadmin:latest'
        ports:
            - 8080:80

    wordpress:
        container_name: 'qnipsel-wordpress'
        depends_on:
            - db
        image: 'wordpress:latest'
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: 'db:3306'
            WORDPRESS_DB_NAME: wordpress_db
            WORDPRESS_DB_USER: wordpress_user
            WORDPRESS_DB_PASSWORD: wordpress_password
        volumes:
            - './docker/wp:/var/www/html'
            - './dist:/var/www/html/wp-content/themes/qnipsel'
