name: Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v2

      # Check and compile SCSS

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Setup Node
        run: npm ci

      - uses: xt0rted/stylelint-problem-matcher@v1

      - name: Check SCSS
        run: npm test

      - name: Run webpack
        env:
          PRODUCTION: ${{ github.ref == 'refs/heads/master' }}
        run: npm run webpack -- --env.PRODUCTION=$PRODUCTION

      # Check and compile PHP

      - name: Check PHP
        uses: chekalsky/phpcs-action@v1
        with:
          enable_warnings: true

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3

      - name: install PHP deps
        run: composer install

      # Sync to server

      - name: Sync to Staging
        if: github.ref == 'refs/heads/develop'
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_IP: ${{ secrets.SSH_IP }}
          GMAPS_API: ${{ secrets.GMAPS_API_KEY }}
        run: |
          rm -rf .git build node_modules scss
          sed -i "s/\*\*\*API KEY\*\*\*/$GMAPS_API/g" page-mapgenerator.php
          sshpass -p "$SSH_PASS" rsync --delete -aqz -e "ssh -o StrictHostKeyChecking=no" . $SSH_USER@$SSH_IP:html/qnipsel-staging/wp-content/themes/templateq

      - name: Sync to Production
        if: github.ref == 'refs/heads/master'
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_IP: ${{ secrets.SSH_IP }}
          GMAPS_API: ${{ secrets.GMAPS_API_KEY }}
        run: |
          rm -rf .git build node_modules scss
          sed -i "s/\*\*\*API KEY\*\*\*/$GMAPS_API/g" page-mapgenerator.php
          sshpass -p "$SSH_PASS" rsync --delete -aqz -e "ssh -o StrictHostKeyChecking=no" . $SSH_USER@$SSH_IP:html/qnipsel/wp-content/themes/templateq
