name: Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: shivammathur/setup-php@master
        with:
          php-version: 7.3

      - name: webpack
        run: |
          npm ci
          npm run webpack

      - name: install PHP deps
        run: |
          composer install

      - name: stage
        if: github.ref == 'refs/heads/develop'
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_IP: ${{ secrets.SSH_IP }}
          GMAPS_API: ${{ secrets.GMAPS_API_KEY }}
        run: |
          rm -rf .git build node_modules scss
          sed -i "s/\*\*\*API KEY\*\*\*/$GMAPS_API/g" page-mapgenerator.php
          sshpass -p "$SSH_PASS" rsync --delete -aqz -e "ssh -o StrictHostKeyChecking=no" . $SSH_USER@$SSH_IP:html/qnipsel-staging/wp-content/themes/templateq

      - name: release
        if: github.ref == 'refs/heads/master'
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_IP: ${{ secrets.SSH_IP }}
          GMAPS_API: ${{ secrets.GMAPS_API_KEY }}
        run: |
          rm -rf .git build node_modules scss
          sed -i "s/\*\*\*API KEY\*\*\*/$GMAPS_API/g" page-mapgenerator.php
          sshpass -p "$SSH_PASS" rsync --delete -aqz -e "ssh -o StrictHostKeyChecking=no" . $SSH_USER@$SSH_IP:html/qnipsel/wp-content/themes/templateq
