name: Check PHP

on: pull_request

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chekalsky/phpcs-action@v1
        with:
          enable_warnings: true
