name: Run Stylelint on pull requests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: xt0rted/stylelint-problem-matcher@v1
      - run: npm ci
      - run: npm test