name: Check SCSS

on: pull_request

jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - uses: xt0rted/stylelint-problem-matcher@v1
      - run: npm ci
      - run: npm test
